residueMap                    = load('residueTypes.mat');
ST3GalI                     = GTEnz([2;4;99;4]);
ST3GalI.resfuncgroup        = residueMap.allresidues('NeuAc');
ST3GalI.resAtt2FG           = residueMap.allresidues('Gal');
galBond                     = GlycanBond('?','1');  
ST3GalI. linkresAtt2FG      = struct('bond',galBond,'anomer','b');
siabond                     = GlycanBond('3','2');
ST3GalI.linkFG              = struct('anomer','a','bond',siabond);
ST3GalI.targetBranch        = glycanMLread('518.26.glycoct_xml');
ST3GalI.isTerminalTarget    = true;
enzViewer(ST3GalI);