residueMap                  = load('residueTypes.mat');
ST3GalIV                     = GTEnz([2;4;99;4]);
ST3GalIV.resfuncgroup        = residueMap.allresidues('NeuAc');
ST3GalIV.resAtt2FG           = residueMap.allresidues('Gal');
galBond                     = GlycanBond('?','1');  
ST3GalIV. linkresAtt2FG      = struct('bond',galBond,'anomer','b');
siabond                     = GlycanBond('3','2');
ST3GalIV.linkFG              = struct('anomer','a','bond',siabond);
ST3GalIV.targetBranch        = glycanMLread('763.38tb.glycoct_xml');
ST3GalIV.isTerminalTarget    = true;
enzViewer(ST3GalIV);