function [groupindex,newdata]=builddendrogram()
% group the glycanspecies based on the rules defined by the enzyme
% information
% input: the enzyme information excel generated by the pathway for HL60
% output: groups of glycanspecies share a certain same features. 

filename   = 'HL60WTN_glycandata.xls';
sheet      = 1;
xlRange    = 'W2:W288';
data       = xlsread(filename,sheet,xlRange); 
newdata    = [];
groupindex = '';
counter    = 0;
for i = 1 : length(data)
    ithvalue = data(i);
    isnew    = 1;
    for j = 1 : length(newdata)
        jthvalue = newdata(j);
        if(isequal(ithvalue,jthvalue))
            isnew                  = 0;
            groupindex{j}(end+1)   = i;
        end
    end
    if(isnew)
        newdata(counter+1,1)  = ithvalue;
        groupindex{counter+1} = i;
        counter               = counter+1;
    end
end
tree     = linkage(newdata,'weighted');

figure()
dendrogram(tree,'ColorThreshold',3,'Orientation','left');
end